### PR TITLE
Feature 2 is developed, please review

### PR DESCRIPTION
**Pull request by kiranpt32**
Feature 2 is developed, please review

### CODE REVIEW

**Comment by bsiva0693** [comment]
please review something is missing

**Comment by kiranpt32** [comment]
> please review something is missing

reviewed, everything is fine. please suggest which is missing

**Comment by bsiva0693** [comment]
please add method to featre-2 like previous

**Comment by kiranpt32** [comment]
> please add method to featre-2 like previous

added the same as you said, pls review

**Review by bsiva0693 — APPROVED** [review]
reviewed, approving this featire-2 for merging to master

**Pull request merged**
